apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: storepage-credential-spc
  namespace: aks-istio-ingress
spec:
  parameters:
    cloudName: ""
    keyvaultName: $AKV_NAME
    objects: |
      array:
        - |
          objectName: test-storepage-bookinfo-key
          objectType: secret
          objectAlias: "test-storepage-bookinfo-key"
        - |
          objectName: test-storepage-bookinfo-crt
          objectType: secret
          objectAlias: "test-storepage-bookinfo-crt"
        - |
          objectName: test-storeinfo-crt
          objectType: secret
          objectAlias: "test-storeinfo-crt"
    tenantId: $TENANT_ID
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $CLIENT_ID 
  provider: azure
  secretObjects:
  - data:
    - key: tls.key
      objectName: test-storepage-bookinfo-key
    - key: tls.crt
      objectName: test-storepage-bookinfo-crt
    - key: ca.crt
      objectName: test-storeinfo-crt
    secretName: storepage-credential
    type: opaque
